apiVersion: v1
kind: Pod
metadata:
  name: label-pod
  labels:
    cloud: aws
    zone: ap-south1
    region: mumbai
  annotations:
    org.docker.kubernetes.image.maintainer: kasevaddi
spec:
  containers:
  - name: nginx
    image: nginx
