apiVersion: v1
kind: Pod
metadata:
  name: env
spec:
  containers:
  - name: ngin
    image: nginx
    env:
    - name: course
      value: aws
    - name: cloud
      value: kasevaddi
    - name: gcp
      value: cloud
    - name: DB_HOST
      value: db.admin.com
    - name: username
      value: kasevaddi
